version: "3"

services:
  db:
    container_name: oracle
    image: store/oracle/database-enterprise:12.2.0.1-slim
    ports:
      - 1521:1521
    volumes:
      - ./ORCL:/ORCL
      - ./Schema:/Schema
